SYMPTOM_LIST = [
    "fever",
    "cough",
    "shortness of breath",
    "chest pain",
    "headache",
    "sore throat",
    "loss of consciousness",
    "fatigue",
    "night sweats",
    "weight loss",
    "nausea",
    "vomiting",
    "dizziness",
    "muscle pain",
    "joint pain",
    "rash",
    "diarrhea",
    "abdominal pain",
    "palpitations",
    "chills",
    "runny nose",
    "congestion",
    "chest pressure",
    "confusion",
    "convulsions",
    "hemoptysis"
]
